/**
 * Created by ben.kl on 2/25/2017.
 */
export const LOAD_COURSES_SUCESS = 'LOAD_COURSES_SUCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREAT_COURSE_SUCCESS = 'CREAT_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS ='UPDATE_COURSE_SUCCESS';
export const BEGIN_AJAX_CALL  = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
